version: '3.9'
services:
  database:
    image: postgres:16
    restart: always
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    shm_size: 128mb
    healthcheck:
      test: pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER} | grep "accepting connections" || exit 1
      interval: 10s
      retries: 60
      timeout: 2s
      start_period: 2s
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - prefect-network

  server:
    image: prefecthq/prefect:2-python3.10
    restart: always
    platform: linux/amd64
    volumes:
      - ./prefect:/root/.prefect
    ports:
      - "${PREFECT_PORT}:${PREFECT_PORT}"
    entrypoint:
      [
        "sh",
        "-c",
        "echo PREFECT_API_DATABASE_CONNECTION_URL=${PREFECT_API_DATABASE_CONNECTION_URL} && prefect server start"
      ]
    environment:
      - PREFECT_UI_URL=http://${PREFECT_HOST}:${PREFECT_PORT}
      - PREFECT_API_URL=http://${PREFECT_HOST}:${PREFECT_PORT}/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres_user:postgres_password@database:5432/prefect
      - PREFECT_API_DATABASE_ECHO=${PREFECT_API_DATABASE_ECHO}
      - PREFECT_API_DATABASE_MIGRATE_ON_START=${PREFECT_API_DATABASE_MIGRATE_ON_START}
    depends_on:
      - database
    networks:
      - prefect-network

networks:
  prefect-network:
    name: prefect-network
