services:
  postgres:
    image: postgres:16
    restart: always
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    shm_size: 128mb
    env_file:
      - .env