# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the Pipfile and Pipfile.lock into the container at /app
COPY Pipfile* /app/

# Install pipenv
RUN pip install pipenv

# Install any needed packages specified in Pipfile.lock
RUN pipenv install --deploy --ignore-pipfile

# Copy the rest of the application code
COPY . /app

# Run the Prefect agent
CMD ["pipenv", "run", "python", "src/my_gh_workflow.py"]