version: '3.9'
services:
  database:
    image: postgres:16
    restart: always
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    shm_size: 128mb
    healthcheck:
      test: pg_isready -q -d $POSTGRES_DB -U $POSTGRES_USER | grep "accepting connections" || exit 1
      interval: 10s
      retries: 60
      timeout: 2s
      start_period: 2s
    env_file:
      - .env
    networks:
      - prefect-network

  server:
    image: prefecthq/prefect:2-python3.10
    restart: always
    platform: linux/amd64
    volumes:
      - ./volumes/prefect:/root/.prefect
    ports:
      - ${PREFECT_PORT}:${PREFECT_PORT}
    entrypoint:
      [ "prefect", "server", "start" ]
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - prefect-network

networks:
  prefect-network:
    name: prefect-network
