version: '3.9'
services:
  agent:
    build: .
    image: prefect-agent:latest
    runtime: nvidia
    env_file:
      - .env
    network_mode: host
    entrypoint:
      [
        "prefect",
        "worker",
        "start",
        "--pool",
        "GPUJobPool"
      ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    volumes:
      - ../prefect:/root/.prefect
      - ../../src:/app
