version: '3.9'
services:
  agent:
    build: .
    image: prefect-agent:latest
    runtime: nvidia
    env_file:
      - .env
    networks:
      - prefect-gpu-agent-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    volumes:
      - ../prefect:/root/.prefect
      - ../../src:/app

networks:
  prefect-gpu-agent-network:
    name: prefect-gpu-agent-network
